# Generated by GeniusQA - Test Login Script
# Created: 1/7/2026, 1:50:18 AM
# This script uses Selenium WebDriver for browser automation

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options

def test_login_script():
    """
    Test Login Script
    
    Automated test script generated from GeniusQA recording
    """
    print(f"Starting script: Test Login Script")
    
    # Setup Chrome driver
    chrome_options = Options()
    # chrome_options.add_argument("--headless")  # Uncomment for headless mode
    driver = webdriver.Chrome(options=chrome_options)
    
    try:
    # Step 1: Navigate to login_page
    driver.get('https://example.com/login')
    time.sleep(1)

    # Step 2: Type in username_field
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, '[data-testid="username_field"], #username_field, .username_field'))
    )
    element.clear()
    element.send_keys('testuser@example.com')
    time.sleep(0.3)

    # Step 3: Click login_button
    element = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, '[data-testid="login_button"], #login_button, .login_button'))
    )
    element.click()
    time.sleep(2)
        
        print("Script execution completed successfully")
    except Exception as error:
        print(f"Script execution failed: {error}")
    finally:
        driver.quit()

if __name__ == "__main__":
    test_login_script()