import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Play, Edit, Trash2, Download, Upload, Search, ChevronDown } from 'lucide-react';
import { GuestModeIndicator } from '../components/GuestModeIndicator';
import { UpgradePrompt } from '../components/UpgradePrompt';
import { useGuestMode } from '../contexts/GuestModeContext';

export const GuestTestCases: React.FC = () => {
  const { scripts, deleteScript, scriptCount, exportScript, exportAllScripts, importScript } = useGuestMode();
  const [searchTerm, setSearchTerm] = useState('');
  const [showImportModal, setShowImportModal] = useState(false);
  const [showExportDropdown, setShowExportDropdown] = useState<string | null>(null);
  const [showBatchExportDropdown, setShowBatchExportDropdown] = useState(false);
  const [selectedScripts, setSelectedScripts] = useState<Set<string>>(new Set());
  const [isSelectionMode, setIsSelectionMode] = useState(false);

  const filteredScripts = scripts.filter(script =>
    script.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Close dropdowns when clicking outside
  React.useEffect(() => {
    const handleClickOutside = () => {
      setShowExportDropdown(null);
      setShowBatchExportDropdown(false);
    };

    if (showExportDropdown || showBatchExportDropdown) {
      document.addEventListener('click', handleClickOutside);
      return () => document.removeEventListener('click', handleClickOutside);
    }
  }, [showExportDropdown, showBatchExportDropdown]);

  const handleDelete = (id: string, name: string) => {
    if (window.confirm(`Are you sure you want to delete "${name}"?`)) {
      deleteScript(id);
      // Remove from selection if it was selected
      setSelectedScripts(prev => {
        const newSet = new Set(prev);
        newSet.delete(id);
        return newSet;
      });
    }
  };

  const handleScriptSelection = (scriptId: string, isSelected: boolean) => {
    setSelectedScripts(prev => {
      const newSet = new Set(prev);
      if (isSelected) {
        newSet.add(scriptId);
      } else {
        newSet.delete(scriptId);
      }
      return newSet;
    });
  };

  const handleSelectAll = () => {
    if (selectedScripts.size === filteredScripts.length) {
      // Deselect all
      setSelectedScripts(new Set());
    } else {
      // Select all filtered scripts
      setSelectedScripts(new Set(filteredScripts.map(script => script.id)));
    }
  };

  const handleExportSelected = (format: 'json' | 'javascript' | 'python') => {
    exportSelectedScripts(Array.from(selectedScripts), format);
    setShowBatchExportDropdown(false);
  };

  const exportSelectedScripts = (scriptIds: string[], format: 'json' | 'javascript' | 'python') => {
    const selectedScriptData = scripts.filter(script => scriptIds.includes(script.id));

    if (selectedScriptData.length === 0) {
      alert('No scripts selected for export');
      return;
    }

    let content: string;
    let filename: string;

    switch (format) {
      case 'json':
        content = JSON.stringify(selectedScriptData, null, 2);
        filename = `geniusqa_selected_scripts_${new Date().toISOString().split('T')[0]}.json`;
        break;
      case 'javascript':
        content = selectedScriptData.map(script => generateJavaScriptCode(script)).join('\n\n');
        filename = `geniusqa_selected_scripts_${new Date().toISOString().split('T')[0]}.js`;
        break;
      case 'python':
        content = selectedScriptData.map(script => generatePythonCode(script)).join('\n\n');
        filename = `geniusqa_selected_scripts_${new Date().toISOString().split('T')[0]}.py`;
        break;
      default:
        alert('Unsupported export format');
        return;
    }

    // Create download link
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Helper function to generate JavaScript code from script
  const generateJavaScriptCode = (script: any): string => {
    return `// Generated by GeniusQA - ${script.name}
// Created: ${new Date(script.createdAt).toLocaleString()}

async function ${script.name.replace(/[^a-zA-Z0-9]/g, '_')}() {
  console.log('Executing script: ${script.name}');
  
  // Script content:
  // ${script.content.split('\n').join('\n  // ')}
  
  // TODO: Implement actual automation logic here
  // This is a template - replace with actual automation code
  
  console.log('Script execution completed');
}

// Execute the script
${script.name.replace(/[^a-zA-Z0-9]/g, '_')}();`;
  };

  // Helper function to generate Python code from script
  const generatePythonCode = (script: any): string => {
    return `# Generated by GeniusQA - ${script.name}
# Created: ${new Date(script.createdAt).toLocaleString()}

import time

def ${script.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}():
    """
    ${script.name}
    
    Script content:
    ${script.content.split('\n').join('\n    ')}
    """
    print(f"Executing script: ${script.name}")
    
    # TODO: Implement actual automation logic here
    # This is a template - replace with actual automation commands
    
    print("Script execution completed")

if __name__ == "__main__":
    ${script.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}()`;
  };

  const toggleSelectionMode = () => {
    setIsSelectionMode(!isSelectionMode);
    if (isSelectionMode) {
      setSelectedScripts(new Set());
    }
  };

  const handleExport = (scriptId: string, format: 'json' | 'javascript' | 'python' = 'json') => {
    exportScript(scriptId, format);
    setShowExportDropdown(null);
  };

  const handleExportAll = (format: 'json' | 'javascript' | 'python' = 'json') => {
    exportAllScripts(format);
    setShowBatchExportDropdown(false);
  };

  const handleImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    // File size validation (5MB limit)
    const maxFileSize = 5 * 1024 * 1024; // 5MB in bytes
    if (file.size > maxFileSize) {
      alert(`Import failed: File size (${(file.size / 1024 / 1024).toFixed(2)}MB) exceeds the maximum limit of 5MB.`);
      event.target.value = '';
      return;
    }

    // File type validation
    const fileExtension = file.name.split('.').pop()?.toLowerCase();
    const supportedExtensions = ['json', 'js', 'javascript', 'py', 'python'];

    if (!fileExtension || !supportedExtensions.includes(fileExtension)) {
      alert(`Import failed: Unsupported file type "${fileExtension}". Supported formats: JSON (.json), JavaScript (.js), Python (.py)`);
      event.target.value = '';
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;

        if (!content || content.trim().length === 0) {
          alert('Import failed: File is empty or contains no readable content.');
          return;
        }

        // Content size validation (after reading)
        if (content.length > maxFileSize) {
          alert(`Import failed: File content is too large (${(content.length / 1024 / 1024).toFixed(2)}MB). Maximum allowed: 5MB.`);
          return;
        }

        let importedData: any;

        switch (fileExtension) {
          case 'json':
            try {
              importedData = JSON.parse(content);
            } catch (parseError) {
              alert(`Import failed: Invalid JSON format. Please check your file syntax.\n\nError: ${parseError instanceof Error ? parseError.message : 'Unknown parsing error'}`);
              return;
            }
            break;
          case 'js':
          case 'javascript':
            // For JavaScript files, create a basic script entry
            importedData = {
              name: file.name.replace(/\.[^/.]+$/, ''),
              content: content
            };
            break;
          case 'py':
          case 'python':
            // For Python files, create a basic script entry
            importedData = {
              name: file.name.replace(/\.[^/.]+$/, ''),
              content: content
            };
            break;
          default:
            // Try to parse as JSON first, then fall back to treating as plain text
            try {
              importedData = JSON.parse(content);
            } catch {
              importedData = {
                name: file.name.replace(/\.[^/.]+$/, ''),
                content: content
              };
            }
        }

        // Attempt import with comprehensive validation
        const importResult = importScript(importedData);
        if (importResult) {
          // Success message based on import type
          if (Array.isArray(importedData)) {
            alert(`Import successful! ${importedData.length} script(s) have been imported.`);
          } else {
            alert(`Import successful! Script "${importedData.name}" has been imported.`);
          }
        }
        // Error messages are handled by the importScript function
      } catch (error) {
        console.error('Import error:', error);
        alert(`Import failed: ${error instanceof Error ? error.message : 'An unexpected error occurred while processing the file.'}`);
      }
    };

    reader.onerror = () => {
      alert('Import failed: Unable to read the selected file. Please try again or choose a different file.');
    };

    reader.readAsText(file);
    setShowImportModal(false);

    // Reset the input value so the same file can be imported again
    event.target.value = '';
  };

  // Close dropdowns when clicking outside
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (showExportDropdown || showBatchExportDropdown) {
        const target = event.target as Element;
        if (!target.closest('.export-dropdown')) {
          setShowExportDropdown(null);
          setShowBatchExportDropdown(false);
        }
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showExportDropdown, showBatchExportDropdown]);

  return (
    <div className="min-h-screen bg-gray-50">
      <UpgradePrompt />

      {/* Header */}
      <div className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Test Scripts</h1>
              <p className="text-gray-600">Manage and organize your test automation scripts</p>
            </div>
            <GuestModeIndicator />
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Actions Bar */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
          <div className="flex items-center space-x-4">
            <Link
              to="/testcases/new"
              className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
            >
              <Plus className="w-4 h-4 mr-2" />
              New Script
            </Link>
            <button
              onClick={() => setShowImportModal(true)}
              className="inline-flex items-center px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium"
            >
              <Upload className="w-4 h-4 mr-2" />
              Import
            </button>
            <button
              onClick={toggleSelectionMode}
              className={`inline-flex items-center px-4 py-2 border rounded-lg font-medium ${isSelectionMode
                ? 'bg-blue-50 border-blue-300 text-blue-700'
                : 'border-gray-300 text-gray-700 hover:bg-gray-50'
                }`}
            >
              {isSelectionMode ? 'Cancel Selection' : 'Select Scripts'}
            </button>
            {isSelectionMode && selectedScripts.size > 0 && (
              <div className="relative export-dropdown">
                <button
                  onClick={() => setShowBatchExportDropdown(!showBatchExportDropdown)}
                  className="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-medium"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Export Selected ({selectedScripts.size})
                  <ChevronDown className="w-4 h-4 ml-1" />
                </button>
                {showBatchExportDropdown && (
                  <div className="absolute left-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10 border">
                    <div className="py-1">
                      <button
                        onClick={() => handleExportSelected('json')}
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        Export as JSON
                      </button>
                      <button
                        onClick={() => handleExportSelected('javascript')}
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        Export as JavaScript
                      </button>
                      <button
                        onClick={() => handleExportSelected('python')}
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        Export as Python
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}
            {!isSelectionMode && (
              <div className="relative export-dropdown">
                <button
                  onClick={() => setShowBatchExportDropdown(!showBatchExportDropdown)}
                  className="inline-flex items-center px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Export All
                  <ChevronDown className="w-4 h-4 ml-1" />
                </button>
                {showBatchExportDropdown && (
                  <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10 border">
                    <div className="py-1">
                      <button
                        onClick={() => handleExportAll('json')}
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        Export as JSON
                      </button>
                      <button
                        onClick={() => handleExportAll('javascript')}
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        Export as JavaScript
                      </button>
                      <button
                        onClick={() => handleExportAll('python')}
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        Export as Python
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="flex items-center space-x-4">
            <div className="relative">
              <Search className="w-4 h-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
              <input
                type="text"
                placeholder="Search scripts..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
          </div>
        </div>

        {/* Storage Usage */}
        <div className="bg-white rounded-lg shadow p-4 mb-6">
          <div className="flex justify-between items-center">
            <div>
              <h3 className="font-medium text-gray-900">Local Storage</h3>
              <p className="text-sm text-gray-600">{scriptCount} of 50 scripts used</p>
            </div>
            <div className="w-32">
              <div className="bg-gray-200 rounded-full h-2">
                <div
                  className="bg-blue-600 h-2 rounded-full transition-all"
                  style={{ width: `${Math.min((scriptCount / 50) * 100, 100)}%` }}
                ></div>
              </div>
            </div>
          </div>
        </div>

        {/* Scripts List */}
        <div className="bg-white rounded-lg shadow">
          {isSelectionMode && filteredScripts.length > 0 && (
            <div className="p-4 border-b border-gray-200 bg-gray-50">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={selectedScripts.size === filteredScripts.length && filteredScripts.length > 0}
                  onChange={handleSelectAll}
                  className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                <span className="ml-2 text-sm font-medium text-gray-700">
                  Select All ({selectedScripts.size} of {filteredScripts.length} selected)
                </span>
              </label>
            </div>
          )}
          {filteredScripts.length > 0 ? (
            <div className="divide-y divide-gray-200">
              {filteredScripts.map((script) => (
                <div key={script.id} className="p-6 hover:bg-gray-50">
                  <div className="flex justify-between items-start">
                    <div className="flex items-start space-x-3 flex-1">
                      {isSelectionMode && (
                        <div className="pt-1">
                          <input
                            type="checkbox"
                            checked={selectedScripts.has(script.id)}
                            onChange={(e) => handleScriptSelection(script.id, e.target.checked)}
                            className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                          />
                        </div>
                      )}
                      <div className="flex-1">
                        <h3 className="text-lg font-medium text-gray-900 mb-1">
                          {script.name}
                        </h3>
                        <p className="text-sm text-gray-600 mb-2">
                          Created {new Date(script.createdAt).toLocaleDateString()} •
                          Updated {new Date(script.updatedAt).toLocaleDateString()}
                        </p>
                        <div className="flex items-center space-x-4 text-sm text-gray-500">
                          <span>Local Storage</span>
                          <span>•</span>
                          <span>Ready to Run</span>
                        </div>
                      </div>
                    </div>

                    {!isSelectionMode && (
                      <div className="flex items-center space-x-2 ml-4">
                        <div className="relative export-dropdown">
                          <button
                            onClick={() => setShowExportDropdown(showExportDropdown === script.id ? null : script.id)}
                            className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded"
                            title="Export Script"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                          {showExportDropdown === script.id && (
                            <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10 border">
                              <div className="py-1">
                                <button
                                  onClick={() => handleExport(script.id, 'json')}
                                  className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                >
                                  Export as JSON
                                </button>
                                <button
                                  onClick={() => handleExport(script.id, 'javascript')}
                                  className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                >
                                  Export as JavaScript
                                </button>
                                <button
                                  onClick={() => handleExport(script.id, 'python')}
                                  className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                >
                                  Export as Python
                                </button>
                              </div>
                            </div>
                          )}
                        </div>
                        <button className="p-2 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded" title="Run Script">
                          <Play className="w-4 h-4" />
                        </button>
                        <button className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded" title="Edit Script">
                          <Edit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(script.id, script.name)}
                          className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded"
                          title="Delete Script"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="p-12 text-center">
              <div className="w-16 h-16 mx-auto bg-gray-100 rounded-full flex items-center justify-center mb-4">
                <Plus className="w-8 h-8 text-gray-400" />
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">
                {searchTerm ? 'No scripts found' : 'No scripts yet'}
              </h3>
              <p className="text-gray-600 mb-6">
                {searchTerm
                  ? 'Try adjusting your search terms'
                  : 'Get started by creating your first test script or importing existing ones'
                }
              </p>
              {!searchTerm && (
                <div className="flex justify-center space-x-4">
                  <Link
                    to="/testcases/new"
                    className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
                  >
                    <Plus className="w-4 h-4 mr-2" />
                    Create Script
                  </Link>
                  <button
                    onClick={() => setShowImportModal(true)}
                    className="inline-flex items-center px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium"
                  >
                    <Upload className="w-4 h-4 mr-2" />
                    Import Script
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Import Modal */}
        {showImportModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Import Script</h3>
              <p className="text-gray-600 mb-4">
                Select a file containing your test script data. Supported formats:
              </p>
              <ul className="text-sm text-gray-600 mb-4 list-disc list-inside">
                <li><strong>JSON</strong> - GeniusQA script format</li>
                <li><strong>JavaScript</strong> - .js files</li>
                <li><strong>Python</strong> - .py files</li>
              </ul>
              <input
                type="file"
                accept=".json,.js,.javascript,.py,.python"
                onChange={handleImport}
                className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
              />
              <div className="mt-4 p-3 bg-blue-50 rounded-lg">
                <p className="text-xs text-blue-700">
                  <strong>Import validation:</strong> Files will be validated and converted to GeniusQA format.
                  Invalid files will show clear error messages.
                </p>
              </div>
              <div className="flex justify-end space-x-3 mt-6">
                <button
                  onClick={() => setShowImportModal(false)}
                  className="px-4 py-2 text-gray-600 hover:text-gray-800 font-medium"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
